services:
  mongodb:
    image: "mongo:4.4.29-focal"
    container_name: mongodb
    restart: always
    env_file:
      - .env.dev
    ports:
      - 27017:27017
    volumes:
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /etc/localtime:/etc/localtime:ro
      - db-data:/data/db
      #- ./scripts:/docker-entrypoint-initdb.d
  seed:
    container_name: seed
    build:
      context: ./backend
      target: dev
    command: npm run seed:up
    environment:
      - MONGO_URI=mongodb://mongo:27017/stockdash
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    profiles:
      - seed
  api:
    container_name: api
    image: stockdash/dev-api
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    restart: always
  dashboard:
    container_name: dashboard
    image: stockdash/dev-dashboard
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - api
    restart: always
    environment:
      - NODE_ENV=development
volumes:
  db-data:
  api-node-modules:
