services:
  mongodb:
    image: "mongo:4.4.29-focal"
    container_name: mongodb
    restart: always
    env_file:
      - .env.dev
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/data/db
      #- ./scripts:/docker-entrypoint-initdb.d
  mongo-seeder:
    image: stockdash/mongo-seeder
    env_file:
      - .env.dev
    build:
      context: ./
      target: dev
    depends_on:
      - mongodb
  api:
    container_name: api
    image: stockdash/dev-api
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - mongodb
  dashboard:
    container_name: dashboard
    image: stockdash/dev-dashboard
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - api
    restart: always
    environment:
      - NODE_ENV=development
volumes:
  db-data:
  api-node-modules:
