services:
  # ************** DATABASE SERVICE **************
  mongodb:
    image: "mongo:4.4.29-focal"
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: stockdash
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/data/db
volumes:
  db-data:
