services:
  mongodb:
    image: "mongo:4.4.29-focal"
    container_name: mongodb
    restart: always
    env_file:
      - .env.dev
    ports:
      - 27017:27017
    volumes:
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /etc/localtime:/etc/localtime:ro
      - db-data:/data/db
      #- ./scripts:/docker-entrypoint-initdb.d
  mongo-seeder:
    image: stockdash/mongo-seeder
    env_file:
      - .env.dev
    build:
      context: ./
      target: dev
    depends_on:
      - mongodb
  api:
    container_name: api
    image: stockdash/api
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/public:/usr/src/app/public
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 4000:4000
    restart: always
  dashboard:
    container_name: dashboard
    image: stockdash/dashboard
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 5173:5173
    depends_on:
      - api
    restart: always
    command: pnpm run dev:local
volumes:
  db-data:
  api-node-modules:
